### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by abnormally-distributed** [aaronjfisher/ggBrain#3]
It says there is no package named tibble, but it's installed. Lots of other errors too. Any way around this?

Error:

> 
> Installing ggBrain
> "C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD build  \
>   "C:\Users\Brandon\AppData\Local\Temp\RtmpCoa5vg\devtools834861e1308e\aaronjfisher-ggBrain-56c931d"  \
>   --no-resave-data --no-manual 
> 
> * checking for file 'C:\Users\Brandon\AppData\Local\Temp\RtmpCoa5vg\devtools834861e1308e\aaronjfisher-ggBrain-56c931d/DESCRIPTION' ... OK
> * preparing 'ggBrain':
> * checking DESCRIPTION meta-information ... OK
> * installing the package to build vignettes
> Warning: running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/Rcmd.exe" INSTALL -l "C:\Users\Brandon\AppData\Local\Temp\RtmpIthv9H\Rinst32206a7a4c6c" --no-multiarch "C:/Users/Brandon/AppData/Local/Temp/RtmpIthv9H/Rbuild322077e2173/ggBrain"' had status 1
>       -----------------------------------
> * installing *source* package 'ggBrain' ...
> ** R
> ** inst
> ** preparing package for lazy loading
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called 'tibble'
> ERROR: lazy loading failed for package 'ggBrain'
> * removing 'C:/Users/Brandon/AppData/Local/Temp/RtmpIthv9H/Rinst32206a7a4c6c/ggBrain'

**Comment by muschellij2** [comment]
This should work.
```r
devtools::install_github("aaronjfisher/ggBrain")
```
I would make sure you have a clean R session before running.
